### ISSUE TITLE
Update the Docs footer License to Creative Commons

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/horusec-docs#95]
Please, could you update the license footer to use Creative Commons instead?

https://creativecommons.org/licenses/by/4.0/

You can use this site as a reference:

https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en

Simple sample of footer

```html
<p>&copy; 2021 Zup IT <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons</a> <a href="https://insights.zup.com.br/politica-privacidade">Privacy Policy</a></p>
```

Ps: In the English version, we need to check the English version of this policy: https://insights.zup.com.br/politica-privacidade

Docs website: https://horusec.io/docs/

**Comment by darwinaraujozup** [comment]
https://github.com/ZupIT/horusec-lp/pull/9

Done!
